config/routes.rb
Rails.application.routes.draw do
  get '/' => 'tags#index', as: :root
  get '/tags' => 'tags#index' 
  get '/tags/:id' => 'tags#show', as: :tag
  get '/destinations/:id' => 'destinations#show', as: :destination
  get '/destination/:id/edit' => 'destinations#edit', as: :edit_destination
  patch '/destinations/:id' => 'destinations#update'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
	belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :destinations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

	def show 
		@destination = Destination.find(params[:id])
		@tag = @destination.tag
	end

	def edit
		@destination = Destination.find(params[:id])
		@tag = @destination.tag
	end

	def update
		@destination = Destination.find(params[:id])
		if @destination.update_attributes destination_params 
			redirect_to(action: 'show', id: @destination.id)
		else
			render 'edit'
		end
	end

private
	
	def destination_params
		params.require(:destination).permit(:name, :description)
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def index 
		@tags = Tag.all
	end

	def show 
		@tag = Tag.find(params[:id]) 
		@destinations = @tag.destinations
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/destinations/edit.html.erb
<div class="header">
	<div class="container">
		<img src="/assets/ruby.png" width="80">
		<h1>TravelApp</h1>
	</div>
</div>


<%= form_for(@destination) do |f| %>
	<%= f.text_area :name %>
	<%= f.text_area :description %>
	<%= f.submit "Make changes" %>
<% end %>

<%= link_to "Back", @tag %>

app/views/destinations/show.html.erb
<div class="header">
	<div class="container">
		<img src="/assets/ruby.png" width="80">
		<h1>TravelApp</h1>
	</div>
</div>

<div class="destination">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">


				<div>
					<%= image_tag @destination.image %>
					<h2><%= @destination.name %></h2>
					<p><%= @destination.description %></p>
					<%= link_to "Back", @tag %>
				</div>

			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tags/index.html.erb
<div class="header">
	<div class="container">
		<%= link_to image_tag('/assets/ruby.png'), :root %>
		<h1>TravelApp</h1>
	</div>
</div>

<div class="tags">
	<div class="container">
		<div class="cards row">
			<% @tags.each do |t| %>
			<div class="card col-xs-4">
				<%= image_tag t.image %>
				<h2> <%= t.title %> </h2>
				<%= link_to "Learn more", tag_path(t) %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/tags/show.html.erb
<div class="header">
	<div class="container">
			
			<%= link_to image_tag('/assets/ruby.png', width: "80"), :root %>

<!-- 			</a><img src="/assets/ruby.png" width="80"></a> -->
		<h1>TravelApp</h1>
	</div>
</div>
<div class="tag">
	<div class="container">
		<h2 class="tag-title"> <%= @tag.title %> </h2>

		<div class="cards row">

			<% @destinations.each do |d| %>
			<div>
				<div class="card col-xs-4">
					<%= image_tag d.image %>
					<h2> <%= d.name %> </h2>
					<p><%= d.description %></p>
					<%= link_to "See more", destination_path(d) %>
					<%= link_to "Edit this destination", edit_destination_path(d) %>
				</div>
			</div>
			<% end %>
			<%= link_to "Back", :root %>
		</div>
	</div>
</div>